### ISSUE TITLE
Talk about division and visibility

### ISSUE THREAD

**Issue by MockingMagician** [romainnorberg/residue#2]
Hello Romain

I open this issue to discuss two points:

- Can a division really be negative? Is there any sense in doing Residue::create(100)->divideBy(-3)? I sincerely ask myself this question and have no idea in either direction.

- All methods are public, but I think that many of them don't make sense to be public.

Waiting for your feedback

**Comment by romainnorberg** [comment]
Hy @MockingMagician 

> Can a division really be negative? Is there any sense in doing Residue::create(100)->divideBy(-3)? I sincerely ask myself this question and have no idea in either direction.

I don't think it brings anything to divide by a negative number, you're right

> All methods are public, but I think that many of them don't make sense to be public.

you are also right, it is an old habit that I have to declare everything public. We can change the methods that can to 'private'

***

can I start working on these 2 points, unless you have already started?

_FYI: I started to set up an online tester to facilitate testing and eventually bug reports: https://residue-online-php-tester.herokuapp.com/ (beta)_

**Comment by MockingMagician** [comment]
Hi @romainnorberg 

Great to be able to test the library live: https://residue-online-php-tester.herokuapp.com/

Deeper, I ask myself new questions that you will surely be able to answer, but the division is still unfair. For example:

```
Residue::create(100)
    ->divideBy(3)
    ->decimal(2)
    ->step(4)

Result: [36, 32, 32]

Residue::create(100)
    ->divideBy(3)
    ->decimal(2)

Result: [33.33, 33.33, 33.34]

```

In addition to being unfair, the distribution can also be with a surplus on the first or last member depending on the number of starts and the size of the step.

I wonder if the distribution should not be fair all the time and leave a remainder in all cases.

Example

```
Residue::create(100)
    ->divideBy(3)
    ->decimal(2)
    ->step(4)

Result: [32, 32, 32]
Reminder: 4

Residue::create(100)
    ->divideBy(3)
    ->decimal(2)

Result: [33.33, 33.33, 33.33]
Reminder: 0.01

```

---

To answer your questions, I have a first draft about visibility, I will pass it on to you. At the same time, I also thought about the idea of fair distribution, but maybe this is outside the scope of this package's definition, or maybe I'm doing the opposite in a way that I don't see.

I'm waiting for your feedback on this point.

**Comment by romainnorberg** [comment]
Hi @MockingMagician 

Thank you in advance for the point concerning visibility

Regarding the division, the initial wish is:

- in the case where the `step` is defined: to distribute equitably and at best in order to avoid having any remainder, for example:

    ```
	Residue::create(340)
	    ->divideBy(3)
	    ->step(20) // [120, 120, 100]


	Residue::create(340)
	    ->divideBy(3)
	    ->decimal(2)
	    ->step(0.5) // [113.5, 113.5, 113]
	```

- without a defined `step`: to distribute fairly according to the number of decimal provided.

We could keep this default behavior and at the same time suggest a way to force the remainder, for example:

```
Residue::create(100)
    ->divideBy(3)
    ->decimal(2)
    ->step(4, <mode>) // <mode> could be ALLOCATE (default behavior) or REMAINDER (your example)
```

With remainder mode:
Result: [32, 32, 32]
Remainder: 4

***

Today this package meets the basic needs of a production project, it probably has bugs on the divisions. I am obviously open to all proposals to improve the portability of this package and its efficiency.

Thank you for your time

**Comment by MockingMagician** [comment]
One more question

What about decimals and step when they "not match" ?

example :

```
Residue::create(100)
    ->divideBy(3)
    ->decimal(2)
    ->step(0.0124)

Result: [33.33, 33.33, 33.33]
Step remainder: float(0.0010000000000057)

Residue::create(100)
    ->divideBy(3)
    ->decimal(2)
    ->step(0.0124)

Result: [33.34, 33.33, 33.33]
Step remainder: float(-0.0059999999999894)
```

As you can see both results are strange...

In the first, all have 33.33 and we've got a stepremainder of 0.0010000000000057 looks prety good but stepRemainder should be more 0.01 in that case

In the second example, first part has 33.34, why not after all but stepRemainder is now negative and has -0.0059999... as value, but it should be more 0 in that case.

So you have this strange behaviors when step and decimals are not matching... It is out of the scope of the initial talk, so I leave it behind for now, we can discuss about later in new issue...

**Comment by MockingMagician** [comment]
> We could keep this default behavior and at the same time suggest a way to force the remainder, for example:
> 
> ```
> Residue::create(100)
>     ->divideBy(3)
>     ->decimal(2)
>     ->step(4, <mode>) // <mode> could be ALLOCATE (default behavior) or REMAINDER (your example)
> ```
> 
> With remainder mode:
> Result: [32, 32, 32]
> Remainder: 4

Il like that way to open the api. In the case of allocate, who have to be allocate ? first , second , third, ...,  last ? 
It have to be consistent and always in the same way.

Update:  you already respond to that, too quick reading... my bad! First to last

**Comment by romainnorberg** [comment]
> So you have this strange behaviors when step and decimals are not matching... It is out of the scope of the initial talk, so I leave it behind for now, we can discuss about later in new issue...

yes i may have noticed this weird behavior while setting up https://residue-online-php-tester.herokuapp.com/ yesterday. I started looking at a bug-fix but didn't have time to work on it today (busy day)

**Comment by MockingMagician** [comment]
Okay @romainnorberg 

So just a recap to see if we sing the same song:

- In case of no step (fairly distribution)

```php
Residue::create(100)
    ->divideBy(3)

Result : [33.33, 33.33, 33.33]
Remainder: 0.01
```

- In case of step, default to ALLOCATE, or choosing REMAINDER

```php
Residue::create(100)
    ->divideBy(3)
    ->step(0.01)

Result : [33.34, 33.33, 33.33]
Remainder: 0


Residue::create(100.01)
    ->divideBy(3)
    ->step(0.01)

Result : [33.34, 33.34, 33.33]
Remainder: 0


Residue::create(100.01)
    ->divideBy(3)
    ->step(0.01, self::MODE_REMAINDER)

Result : [33.33, 33.33, 33.33]
Remainder: 0.02
```

Can you confirm I'm singing the song ^^ ?

**Comment by MockingMagician** [comment]
> Residue::create(100)
>     ->divideBy(3)
>     ->decimal(2)
>     ->step(4, <mode>) // <mode> could be ALLOCATE (default behavior) or REMAINDER (your example)

And about the mode on split ? 

```php
Residue::create(100.01)
    ->divideBy(3)
    ->step(0.01)
    ->split(<mode>) default to allocate
```

As is, with orwithout step, the api will stay consistent ... :thinking:

**Comment by romainnorberg** [comment]
yes @MockingMagician, very nice! (I was responding with the solution: `Residue::create(100, self::MODE_REMAINDER)` but your solution is better) 

So:

- In case of no step :

```php
Residue::create(100)
    ->divideBy(3)
    ->split() // default to allocate

Result : [33.33, 33.33, 33.34] // we allocate the remainder to the last element to keep the advantage of \Generator (unless there is another solution ?)
Remainder: 0

/////

Residue::create(100) // fairly distribution
    ->divideBy(3)
    ->split(self::MODE_FORCE_REMAINDER)

Result : [33.33, 33.33, 33.33] 
Remainder: 0.01
```

- In case of step, default to ALLOCATE, or choosing MODE_FORCE_REMAINDER

```php
Residue::create(100)
    ->divideBy(3)
    ->step(0.01)
    ->split() // default to allocate

Result : [33.34, 33.33, 33.33] // first to last 
Remainder: 0

/////

Residue::create(100.01)
    ->divideBy(3)
    ->step(0.01)
    ->split() // default to allocate

Result : [33.34, 33.34, 33.33] // first to last 
Remainder: 0

/////

Residue::create(100.01)
    ->divideBy(3)
    ->step(0.01)
    ->split(self::MODE_FORCE_REMAINDER) // default to allocate

Result : [33.33, 33.33, 33.33]
Remainder: 0.02
```

What do you think ?

In this case, we have to update `toArray()` method (`split()` returns a \Generator, and toArray returns `iterator_to_array($this->split()`)

**Comment by MockingMagician** [comment]
Yeah @romainnorberg I think we are so close to a clean solution

I'm always a bit annoyed about the difference in behavior in the allocation...

We have to find a solution so that the behavior is the same no matter if the step is defined or not...

Need to think about it... I have a feeling about to factorize in such a way splitWithoutStep and splitWithStep. I just don't clearly see the good way at this point

**Comment by MockingMagician** [comment]
A good start for this job is to implement our contract for Residue, so we can already define what is public and what is not (the not defined in our contract) : 

```php
<?php


namespace Romainnorberg\Residue\Contracts;


use Generator;

interface ResidueInterface
{
    public const MODE_ALLOCATE = 'allocate';
    public const MODE_EQUITY = 'equity';
    public const MODES = [
        self::MODE_ALLOCATE,
        self::MODE_EQUITY,
    ];

    public function divideBy(int $divider): self;
    public function step(float $step): self;
    public function decimal(int $decimal): self;
    public function split(string $mode = self::MODE_ALLOCATE): Generator;
    public function getRemainder(): float;
    public function toArray(): array;
}

```

**Comment by MockingMagician** [comment]
> ```
> Result : [33.33, 33.33, 33.34] // we allocate the remainder to the last element to keep the advantage of \Generator (unless there is another solution ?)
> ```

Cleary want to keep generator... but maybe a try without to see if something can be done... then rewrite in the way of functional generator if possible

I gonna work on potential factorization of splitWith and splitWithout...

**Comment by romainnorberg** [comment]
first, thank you already for your involvement!  We have tests so we can refactor as we want,  if we can make this package more robust, more clean and more cohesive while keeping it light, I am for.

I'm ok to implement a contract like your example `ResidueInterface`, I can't wait to see your work on this part 👍

**Comment by MockingMagician** [comment]
Hi @romainnorberg 

> first, thank you already for your involvement!

This package can be usefull for one of my project (On the condition that it works without edge effect). And I must admit that I really liked your code, I found it rather clean and I didn't see a single "else", it's so beautiful and rare that it made me want to take part in your project.

> I'm ok to implement a contract like your example ResidueInterface, I can't wait to see your work on this part :+1:

I hope to come back soon with a (start of) solution

**Comment by MockingMagician** [comment]
I think I have the shot :tada: seems good on the first look. There is no unexpected behaviors on the first test bench. Some stufs are always a bit drafty, but the spirit is there.

Waiting for your review and comments https://github.com/romainnorberg/residue/pull/3

**Comment by romainnorberg** [comment]
Hy @MockingMagician feedbacks here: https://github.com/romainnorberg/residue/pull/3#pullrequestreview-510953846 
-> nice work 🎉

**Comment by romainnorberg** [comment]
Hy @MockingMagician can we close this issue ? I think it's covered by your PR #3

**Comment by MockingMagician** [comment]
@romainnorberg yeap nothing to discuss more here ^^
