### ISSUE TITLE
About edge case

### ISSUE THREAD

**Issue by MockingMagician** [romainnorberg/residue#4]
Hi @romainnorberg,

Sorry for a so soon come back of myself to discuss about a new edge case :

Consider this test :

```php
yield [
    100, // value
     5, // divide
     null, // decimal value
     45, // step
     [
         45,
         45,
         0,
         0,
         0,
     ], // expected result
     10, // remainder
];
```

Of course, it pass perfectly, but maybe it should not... nothing to distribute to 3, 4, and 5 part seems strange in a way...

What do you think ?

According to the set of equation, we can quickly determine if everyone will have something distributed. 

The only check to do, it's to check if Divder is greater than Ns. If it is, we can throw an error...Of course, if we consider that this is the expected behaviour.

In the same way, this is a fully valid test :

```php
yield [
    100, // value
     5, // divide
     null, // decimal value
     150, // step
     [
         0,
         0,
         0,
         0,
         0,
     ], // expected result
     100, // remainder
];
```

**Comment by romainnorberg** [comment]
Hi @MockingMagician 🤝 

I don't know if it's our role to trig a fatal error in this case, we assume that all our users are responsible.
For me, this is the exepected behavior.

We could imagine triggering a notice (eg.: `trigger_error('xxxx', E_USER_NOTICE);`) but with the possibility of deactivating it _(like a verbose mode)_ ?

**Comment by MockingMagician** [comment]
Hi @romainnorberg 

> I don't know if it's our role to trig a fatal error in this case, we assume that all our users are responsible.

I think you are right, my mind always want to prevent for these kinds of happening, but after all it could be a user case... or just "a think before acting"

> We could imagine triggering a notice (eg.: trigger_error('xxxx', E_USER_NOTICE);)

Most of user land convert notice to exception (at least in dev mode), so I don't think we improve a lot there... I just agree with your first argument.

Case closed :sunglasses:
